[package]
name = "xsint"
description = "Lightweight RISC-V Interpreter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "xsint"
path = "src/main.rs"

[[test]]
name = "tokenizer"
path = "tests/tokenization.rs"

[dependencies]
bitflags = "1.3"
regex = "1"
lazy_static = "1.4"